image: node:latest

stages:
  - build
  - generate
  - lint
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

linter:
  stage: lint
  script: npm run lint
